### PR TITLE
add proposal: What Are You Running? PuppetDB Knows.

### PR DESCRIPTION
**Pull request by richburroughs**

### CODE REVIEW

**Comment by purpleidea** [comment]
@toshywoshy s/chef/puppet/ ?

**Comment by toshywoshy** [comment]
@purpleidea thanks, I did indeed add the wrong label

**Comment by KrisBuytaert** [comment]
We have been discussing your talk proposal and wonder if you would be interested in giving it as an Ignite.
Ignites are 5 minute talks with 20 autoforwarding slides every 15 seconds.
They are the perfect vehicle to get your focussed message to a larger audience !

If you are interested, please let us know by updating this PR.

**Comment by richburroughs** [comment]
@KrisBuytaert Yes we can do that one as an Ignite :) Sounds great.

**Pull request merged**
