### PR TITLE
Event-Driven Infrastructure talk proposal

### PR DESCRIPTION
**Pull request by cachedout**

### CODE REVIEW

**Comment by purpleidea** [comment]
Hi @cachedout Thanks for your proposal. The topic sounds interesting, however the abstract was extremely vague and hand wavy. Do you think you could include more detail, eg: what tools you're using for this, what experience you have (eg: why we should trust your opinion on this for example) and some concrete examples perhaps.

Just my opinions, other reviewers might have different thoughts.

Thanks!

**Comment by purpleidea** [comment]
PS Just noticed you are a "SaltStack maintainer" so I'll assume it's related to that, but including that info in the abstract would be helpful. Thanks :)

**Comment by cachedout** [comment]
@purpleidea After re-reading this, I completely agree with you. It's been a very busy week and I apologize for not completely being clear. I'll make some modifications to this proposal per your suggestion now that I have a little more time. :] Thanks for the feedback!

**Comment by purpleidea** [comment]
@cachedout No apology needed, it wasn't meant as a "diss", but rather a "is this generic nonsense" or "is this going to be a great talk but not obvious from abstract". I am definitely in the "event-driven config management space" so I'd really like to get your perspective. I hope you have lots of awesome demos planned! Link us to a previous variant of this talk (eg: a recording) if you've got one!

Thanks!

**Comment by cachedout** [comment]
@purpleidea I didn't take it negatively at all. No worries! :]

I'll likely do a SaltStack demo (as mentioned) and perhaps some others, time permitting. I gave an early version of this talk at a DevOpsDays event last year but there's no recording of it that I'm aware of.

**Comment by purpleidea** [comment]
@cachedout That's too bad about no video, but I hope I can make it to your talk if it gets accepted! :)


(As a very lame, cheap plug, I'm also working on an event based approach to config management, except it's not as mature and far along as salt stack yet. I actually strongly considered salt stack before I embarked on the journey, but would love to discuss more if this interests you. I'm in #mgmtconfig on Freenode, feel free to ping.)

**Comment by cachedout** [comment]
@purpleidea Yes, I have come across `mgmt`. It looks very cool! Would love to see a demo if we both make it up to CfgMgmgtCamp this year. Cheers!

**Comment by KrisBuytaert** [comment]
As you might have noticed we merged your Pull Request,
That means we have accepted your talk Proposal for CfgMgmtCamp PDX.

The next step would be for you to confirm us via email

cfp@cfgmgmtcamp.eu  that you can be present in PDX on August 3rd and you still want to present.

After that we will follow up with more details

**Pull request merged**
