### PR TITLE
Taming Terraform workflow using modules and Github for change managem…

### PR DESCRIPTION
**Pull request by anubhavmishra**
…ent.

### CODE REVIEW

**Comment by anubhavmishra** [comment]
@toshywoshy I think I got this in before the deadline. Haven't seen any activity on this yet. Just wondering what the status was?

**Comment by KrisBuytaert** [comment]
@anubhavmishra  the CFP isn't closed yet.

**Comment by anubhavmishra** [comment]
thanks @KrisBuytaert!

**Comment by KrisBuytaert** [comment]
As you might have noticed we merged your Pull Request,
That means we have accepted your talk Proposal for CfgMgmtCamp PDX.

The next step would be for you to confirm us via email

cfp@cfgmgmtcamp.eu  that you can be present in PDX on August 3rd and you still want to present.

After that we will follow up with more details

**Comment by anubhavmishra** [comment]
@KrisBuytaert I just emailed cfp@cfgmgmtcamp.eu :)

**Pull request merged**
